USE [master]
GO
/****** Object:  Database [NUEVO_MANTENIMIENTO_PRODUCTO]    Script Date: 7/23/2021 3:34:29 PM ******/
CREATE DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NUEVO_MANTENIMIENTO_PRODUCTO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\NUEVO_MANTENIMIENTO_PRODUCTO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NUEVO_MANTENIMIENTO_PRODUCTO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\NUEVO_MANTENIMIENTO_PRODUCTO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NUEVO_MANTENIMIENTO_PRODUCTO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET ARITHABORT OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET  MULTI_USER 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET QUERY_STORE = OFF
GO
USE [NUEVO_MANTENIMIENTO_PRODUCTO]
GO
/****** Object:  Table [dbo].[CATEGORIA]    Script Date: 7/23/2021 3:34:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIA](
	[IDPRODUCTO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO]  AS ('CT'+right('00'+CONVERT([varchar],[IDPRODUCTO]),(6))),
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDPRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CATEGORIA] ON 
GO
INSERT [dbo].[CATEGORIA] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION]) VALUES (4, N'PINTURAS TUCAN', N'PINTURAS AMARILLAS')
GO
SET IDENTITY_INSERT [dbo].[CATEGORIA] OFF
GO
/****** Object:  StoredProcedure [dbo].[spbuscar_categoria]    Script Date: 7/23/2021 3:34:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spbuscar_categoria]
@textobuscar varchar(50)
as
select * from CATEGORIA 
where NOMBRE like @textobuscar + '%'
GO
/****** Object:  StoredProcedure [dbo].[speditar_categoria]    Script Date: 7/23/2021 3:34:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[speditar_categoria]
@idproducto int,
@codigoproducto varchar(6),
@nombre varchar(50),
@descripcion varchar(max)
as
update CATEGORIA set NOMBRE=@nombre, DESCRIPCION=@descripcion
where IDPRODUCTO=@idproducto
GO
/****** Object:  StoredProcedure [dbo].[speliminar_categoria]    Script Date: 7/23/2021 3:34:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[speliminar_categoria]
@idproducto int
as
delete from CATEGORIA
where IDPRODUCTO=@idproducto
GO
/****** Object:  StoredProcedure [dbo].[spinsertar_categoria]    Script Date: 7/23/2021 3:34:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[spinsertar_categoria]
@idproducto int output,
@codigoproducto varchar(6) output,
@nombre varchar(50),
@descripcion varchar(max)
as
insert into CATEGORIA  (nombre, descripcion) values(@nombre, @descripcion)
GO
/****** Object:  StoredProcedure [dbo].[spmostrar_categoria]    Script Date: 7/23/2021 3:34:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[spmostrar_categoria]
as
select top 200 * from CATEGORIA
ORDER BY IDPRODUCTO asc
GO
USE [master]
GO
ALTER DATABASE [NUEVO_MANTENIMIENTO_PRODUCTO] SET  READ_WRITE 
GO
